version: '3.9'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '15432:5432'
    env_file:
      - .env
    volumes: 
        - pgdata:/var/lib/postgres/data

volumes: 
    pgdata: {}
