version: '3.9'
services:
  postgres:
    image: postgres:13        
    container_name: postgres        
    restart: always
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE_NAME}
        PG_DATA: /var/lib/postgresql/data
    ports:
        - 15432:5432
    env_file:
        - .env
    volumes:             
        - pgdata:/var/lib/postgresql/data
    networks: 
        postgres_network:
            aliases: 
                - postgres_host

volumes:
    pgdata:
networks: 
    postgres_network:
        name: postgres_net
        driver: bridge
